os: linux
dist: xenial
group: beta
language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true
  include:
    - stage: tests
      name: "Unit tests (using Truffle)"
      script: npm run test